spring.application.name=Learn-Restful-Api

spring.mvc.hiddenmethod.filter.enabled=true

spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update

spring.datasource.username=root
spring.datasource.password=07082004aA@

duong.jwt.base64-secret=aGt+l495xiSEUkVSDYyuaQDPm8Emb//pk7+SUpUaAjM=
#1day
duong.jwt.access-token-validity-in-seconds=86400
duong.jwt.refresh-token-validity-in-seconds=86400

# default page size
spring.data.web.pageable.default-page-size=10

# max page size
spring.data.web.pageable.max-page-size=100

#false: start with 0; true: start with 1
spring.data.web.pageable.one-indexed-parameters=true

spring.servlet.multipart.max-request-size=50MB

spring.servlet.multipart.max-file-size=50MB

#base path
duong.upload-file.base-uri=file:///D:/upload/

#Gmail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vanduonghaha12@gmail.com
spring.mail.password=vstbsuxabiukwznu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true









