spring.application.name=Learn-Resful-Api
server.port = 3000
spring.mvc.hiddenmethod.filter.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/springdemoresful
spring.datasource.username=root
spring.datasource.password=07082004aA@
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql=true





