spring.application.name=Learn-Restful-Api-Test
server.port = 8000
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/testdata?createDatabaseIfNotExist=true








